### ISSUE TITLE
mkdocs serve not working on mkdocs 1.2

### ISSUE THREAD

**Issue by sirchampsblanc** [backstage/mkdocs-monorepo-plugin#49]
I updated my current virtual env to use mkdocs 1.2 (i'm testing the new analytics feature since i can't generate a UA-XXXXXX to use with older versions) and i get an error at the end of the building while serving (mkdocs build works fine):

```
File ".venv/lib/python3.6/site-packages/mkdocs_monorepo_plugin/plugin.py", line 67, in on_serve
    buildfunc = list(server.watcher._tasks.values())[0]['func']
AttributeError: 'LiveReloadServer' object has no attribute 'watcher'
```
Redirected from https://github.com/mkdocs/mkdocs/issues/2446#issuecomment-856059523

**Comment by oprypin** [comment]
FYI:
* A "modern" fix that is compatible only with MkDocs 1.1.1 and the new 1.2:
https://github.com/mkdocstrings/mkdocstrings/commit/e8d657352aec2e519971ef70903c0cdb72bb4418
* A fix including more legacy versions:
https://github.com/fralau/mkdocs_macros_plugin/commit/4bf847b3460471ee9cf2559cd5562954f378fe3b

**Comment by PaulienVa** [comment]
Has anyone had a look at this issue? I am encountering the same issue using the following dependencies:
- mkdocs version 1.2.1
- mkdocs-monorepo-plugin version 0.4.15
- markdown version 3.2.1

**Comment by sirchampsblanc** [comment]
Any updates on this?

**Comment by nghiaho12** [comment]
I also have this error. Here's my workaround (no guarantee on correctness!). Edit plugin.py, modify def_on_serve

```
def on_serve(self, server, config, **kwargs):
    #buildfunc = list(server.watcher._tasks.values())[0]['func']

    # still watch the original docs/ directory
    server.watch(self.originalDocsDir) #, buildfunc)

    # watch all the sub docs/ folders
    for _, docs_dir, yaml_file in self.resolvedPaths:
        server.watch(yaml_file) #, buildfunc)
        server.watch(docs_dir) #, buildfunc)
```

It appears to work for my limited test case. This is mentioned in site-packages/mkdocs/livereload/__init__.py

```
def watch(self, path, func=None, recursive=True):
    """Add the 'path' to watched paths, call the function and reload when any file changes under it."""
    path = os.path.abspath(path)
    if func in (None, self.builder):
        func = self.builder
    else:
        warnings.warn(
            "Plugins should not pass the 'func' parameter of watch(). "
            "The ability to execute custom callbacks will be removed soon.",
            DeprecationWarning,
            stacklevel=2,
        )
```

**Comment by iamEAP** [comment]
Thanks for the patience y'all!  You should be good once you bump to `0.4.16` of this plugin.

**Comment by marc0olo** [comment]
> Thanks for the patience y'all! You should be good once you bump to `0.4.16` of this plugin.

the time couldn't be better! thanks =)

**Comment by estahn** [comment]
Indeed, I was just debugging this yesterday :)
